### ISSUE TITLE
Collection of HEP/Astro related ML papers.

### ISSUE THREAD

**Issue by kabartay** [escape2020/school2021#120]
**A Living Review of Machine Learning for Particle Physics**

[https://github.com/iml-wg/HEPML-LivingReview](https://github.com/iml-wg/HEPML-LivingReview)

It would be great if you have time to **contribute** to this project. 

_Modern machine learning techniques, including deep learning, is rapidly being applied, adapted, and developed for high-energy physics. The goal of this document is to provide a nearly comprehensive list of citations for those developing and applying these approaches to experimental, phenomenological, or theoretical analyses. As a living document, it will be updated as often as possible to incorporate the latest developments. A list of proper (unchanging) reviews can be found within. Papers are grouped into a small set of topics to be as useful as possible. Suggestions are most welcome._

**Comment by kabartay** [comment]
Just a piece of information.

**Comment by bkmgit** [comment]
Nice, also from the same group is:
https://github.com/iml-wg/HEP-ML-Resources
