### ISSUE TITLE
[BUG] Problem: nothing provides xrootd needed by uproot-4.0.0-pyhd8ed1ab_0

### ISSUE THREAD

**Issue by NicoSerranoP** [escape2020/school2021#19]
**Describe the bug**

I am trying to setup the environment following the README.md instructions of the repository. When I execute:
```
mamba env create -f environment.yml
```
I get the following output:
```
conda-forge/win-64       Using cache
conda-forge/noarch       Using cache
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/win-64            [====================] (00m:00s) No change
pkgs/main/win-64         [====================] (00m:00s) No change
pkgs/msys2/noarch        [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/msys2/win-64        [====================] (00m:00s) No change
default/noarch           [====================] (00m:00s) No change
default/win-64           [====================] (00m:00s) No change


Looking for: ['anaconda-client', 'astropy=4.2', 'conda-build', 'cython', 'h5py', 'ipython', 'jupyter', 'jupyterlab', 'm]


Encountered problems while solving.
Problem: nothing provides xrootd needed by uproot-4.0.0-pyhd8ed1ab_0
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - `conda --version`: conda 4.10.1
 - `python --version`: Python 3.8.8

**Comment by vuillaut** [comment]
Hi @NicoSerranoP 
Thank you for reporting and opening an issue.

When have you cloned the repository?
Could you try to update, please?
```
git pull
```
And then try again.

**Comment by NicoSerranoP** [comment]
It is working now (June 4th) :D 

I cloned the repo yesterday and I have been trying to find a solution since then. Thank you for solving it :)

**Comment by maxnoe** [comment]
Conda hat a big Server Problem yesterday,  which might be the reason here
