### ISSUE TITLE
mamba not found on windows

### ISSUE THREAD

**Issue by vuillaut** [escape2020/school2021#20]
> 
> 
> Correct: `mamba`.
> 
> Wrong: `memba`
> 
> To copy: `conda install -c conda-forge mamba`

Sorry , I used mamba but same error again
![error](https://user-images.githubusercontent.com/58546104/120861171-26b68d00-c59c-11eb-8de6-bc78542dbbe0.JPG)

_Originally posted by @shandizp in https://github.com/escape2020/school2021/issues/16#issuecomment-854990699_

**Comment by vuillaut** [comment]
Hi  @shandizp,

Could you try creating the env without mamba, please?
So just
```
cd school2021
conda env create -f environment.yml
conda activate eschool2021
```

**Comment by shandizp** [comment]
> 
> 
> Hi @shandizp,
> 
> Could you try creating the env without mamba, please?
> So just
> 
> ```
> cd school2021
> conda env create -f environment.yml
> conda activate eschool2021
> ```

Hi, I am so sorry I still have a problem. There is sslError. I have screenshots here.
Thank you.
![2e](https://user-images.githubusercontent.com/58546104/120903140-a2c2da80-c659-11eb-80ba-196a88eb1e36.JPG)
![error1](https://user-images.githubusercontent.com/58546104/120903146-a7878e80-c659-11eb-8755-8bf96a651ffd.JPG)

**Comment by shandizp** [comment]
Hi, what should I do I still have an Error?

**Comment by maxnoe** [comment]
Write me in slack, that will be faster ;)
