### ISSUE TITLE
"An unexpected error has occurred" when building environment.yml

### ISSUE THREAD

**Issue by blackbianca** [escape2020/school2021#21]
When I type in the command
**mamba env create -f environment.yml**
in order to build the environment from the yml file, I get an error log that ends with "An unexpected error has occurred. Conda has prepared the above report." The log file is attached here.

[log.txt](https://github.com/escape2020/school2021/files/6602133/log.txt)

**Comment by maxnoe** [comment]
The file does not show any actual error. Could you try to run the command again and show the actual error? Either by copying the output from the terminal our making a screenshot.

**Comment by blackbianca** [comment]
Thanks for your answer. The file I attached is exactly the output of the terminal, here are the screenshots. I apologize if I'm misunderstanding your request.

![1](https://user-images.githubusercontent.com/56002125/120889788-15eb3300-c5ff-11eb-86f3-63b4800f257c.png)
![2](https://user-images.githubusercontent.com/56002125/120889790-1683c980-c5ff-11eb-9bd7-b15a0f8c9704.png)

**Comment by maxnoe** [comment]
@blackbianca The actual error message should be above. Can you show everything starting from the point where you entered the command?

**Comment by blackbianca** [comment]
Yes, now I get it. I was misleading the command line with another line. My bad, I'm very sorry.

[log.txt](https://github.com/escape2020/school2021/files/6602716/log.txt)

![A](https://user-images.githubusercontent.com/56002125/120895746-b4d35780-c61e-11eb-8f79-62bfaf8f4fee.png)
![B](https://user-images.githubusercontent.com/56002125/120895747-b6048480-c61e-11eb-8d03-25e6a738bb63.png)

**Comment by maxnoe** [comment]
That's strange. It might be that you have a broken package cache and this is why mamba cannot find the packages.

Can you try clearing the cache using:

```
mamba clean --all --yes
```

and then retry the environment creation?

**Comment by vuillaut** [comment]
There has been several issues with Windows and mamba already.
You may try to skip mamba and go for
```
conda env create -f environment.yml
```

**Comment by blackbianca** [comment]
Clearing the cache does not seem to work, but the error output is slightly different.

[log3.txt](https://github.com/escape2020/school2021/files/6603097/log3.txt)


I also tried using conda instead of mamba to create the environment, but again I think something fails. Here is the log. 

[log2.txt](https://github.com/escape2020/school2021/files/6603084/log2.txt)

I tried typing anyway

`conda activate eschool2021`

but no environment with such name is found.

**Comment by maxnoe** [comment]
We "solved" this problem by removing packages for one lecture from the environment and putting those in a separate file.

Can you update you repo using `git pull` and rerun the environment creation using mamba?

**Comment by blackbianca** [comment]
Hi, I updated the repository and rerun environment creation with mamba, but I get again an error

[log4.txt](https://github.com/escape2020/school2021/files/6603954/log4.txt)

So I tried building with conda instead of mamba and this time it worked, and I was then able to activate the environment correctly.

**Comment by maxnoe** [comment]
@blackbianca Grat that worked. Looking at the error, it seems mamba was unable to get or read the package database.  It reports 0 packages in each of the channels, that has to be some network or caching issue.

So maybe, again cleaning everything might help.
