### ISSUE TITLE
[COURSE BUG] - youtube lecture not displayed in pages

### ISSUE THREAD

**Issue by vuillaut** [escape2020/school2021#29]
The recorded lecture does not appear embedded in the welcome page:
https://escape2020.github.io/school2021/posts/welcome/

What am I doing wrong?

**Comment by artfisica** [comment]
I go to take a look

**Comment by YouSchnabel** [comment]
Try this link: https://www.youtube.com/watch?v=TUrJ_IudVx8, your link redirects there.

**Comment by devine73** [comment]
Hi, at least you can try the non embeded way :
`[![ESCAPE Intro](https://img.youtube.com/vi/TUrJ_IudVx8/0.jpg)](https://www.youtube.com/watch?v=TUrJ_IudVx8 "ESCAPE Introduction")`

**Comment by artfisica** [comment]
Hi again,

Pull https://github.com/escape2020/school2021/pull/30 allow to visualise the video :)

**Comment by vuillaut** [comment]
Thanks! Solved
