### ISSUE TITLE
I can't set the environment

### ISSUE THREAD

**Issue by ignacionegueruela** [escape2020/school2021#39]
I cannot set the school environment. I am using Fedora/Linux with miniconda

If I run mamba env create -f environment.yml, I get an error (see below). It is exactly the same with conda. I do not understand what it is complaining about.

Any help highly appreciated, as I am stuck here.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 81, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 165, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 142, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/home/ignacio/miniconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 103, column 65:
         ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... 
                                             ^ (line: 103)

`$ /home/ignacio/miniconda3/bin/mamba create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/ignacio/miniconda3/bin/conda
             CONDA_PREFIX=/home/ignacio/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/ignacio/miniconda3/bin/python
               CONDA_ROOT=/home/ignacio/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 GDL_PATH=+/usr/share/gnudatalanguage
          LD_LIBRARY_PATH=/usr/lib64/mpich/lib
                  MANPATH=/usr/share/man:/usr/share/man/mpich-x86_64::
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/sh
                          are/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/ignacio/miniconda3/bin:/home/ignacio/miniconda3/bin:/home/ignaci
                          o/miniconda3/condabin:/usr/libexec/python3-sphinx:/usr/lib64/qt-3.3/bi
                          n:/usr/lib64/mpich/bin:/usr/share/Modules/bin:/home/ignacio/.cargo/bin
                          :/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin
                          :/usr/local/fv5.4:/home/ignacio/newp2pp/p2pp-3.4.2/bin:/home/ignacio/p
                          2pp/p2pp-2.13.1/bin:/home/ignacio/gasgano-2.4.3/bin:/usr/local/SweetHo
                          me3D-5.4:/usr/local/fv5.4:/usr/local/starjava/bin:/usr/local/starjava/
                          bin/splat:/usr/local/starjava/bin/sog:/usr/local/starjava/bin/jsky:/us
                          r/local/starjava/bin/ndtools:/usr/local/mendeleydesktop-1.19.4-linux-x
                          86_64/bin:/home/ignacio/.local/bin:/usr/local/miniconda2/bin:/usr/loca
                          l/bin:/usr/local/fv5.4:/home/ignacio/newp2pp/p2pp-3.4.2/bin:/home/igna
                          cio/p2pp/p2pp-2.13.1/bin:/home/ignacio/gasgano-2.4.3/bin:/usr/local/Sw
                          eetHome3D-5.4:/usr/local/fv5.4:/usr/local/starjava/bin:/usr/local/star
                          java/bin/splat:/usr/local/starjava/bin/sog:/usr/local/starjava/bin/jsk
                          y:/usr/local/starjava/bin/ndtools:/usr/local/mendeleydesktop-1.19.4-li
                          nux-x86_64/bin:/home/ignacio/.local/bin:/usr/local/miniconda2/bin:/usr
                          /local/miniconda2/bin
          PKG_CONFIG_PATH=/usr/lib64/mpich/lib/pkgconfig
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /home/ignacio/miniconda3
            shell level : 1
       user config file : /home/ignacio/.condarc
 populated config files : /home/ignacio/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.6.13=0
                          __glibc=2.29=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ignacio/miniconda3  (writable)
      conda av data dir : /home/ignacio/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/sherpa/linux-64
                          https://conda.anaconda.org/sherpa/noarch
                          https://conda.anaconda.org/cxc/linux-64
                          https://conda.anaconda.org/cxc/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ignacio/miniconda3/pkgs
                          /home/ignacio/.conda/pkgs
       envs directories : /home/ignacio/miniconda3/envs
                          /home/ignacio/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Linux/5.6.13-100.fc30.x86_64 fedora/30 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by vuillaut** [comment]
Hi
Could you try creating the environment without using mamba?
So
```
git pull
conda update -n base --all
conda env create -f environment.yml
```

**Comment by ignacionegueruela** [comment]
It gives exactly the same error with conda.

**Comment by maxnoe** [comment]
@ignacionegueruela If you want, I can have a look in gathertown

**Comment by ignacionegueruela** [comment]
Thanks for the help. I really don't know how to move around in GatherTown.

**Comment by maxnoe** [comment]
Somehow the `environment.yml` was the html file downloaded from github, which created this error.
