### ISSUE TITLE
Docker doesn't finish it's installation

### ISSUE THREAD

**Issue by juanessao2000** [escape2020/school2021#44]
When trying to install the Docker environment, it asks me for the update of WSL in Windows, and so I did. However, when I open Docker it shows me to copy the following command so that I copy it on the terminal

![image](https://user-images.githubusercontent.com/85579769/121233275-1cc0b280-c858-11eb-84b1-f042b65297cd.png)

but when I run the command con my CMD terminal in Windows, it shows me this error

![image](https://user-images.githubusercontent.com/85579769/121233386-3eba3500-c858-11eb-8aba-36c569ae617b.png)

I tried to look for this error in StackOverflow and there I found that I could use the command 

`"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon`

but it did not work.

If someone knows how to solve this problem, I would be very grateful.

**Comment by juanessao2000** [comment]
It was solved in the slack 'enviroment setup'. Thank you, very much!

**Comment by artfisica** [comment]
Thanks for the feedback; this is great!
