### ISSUE TITLE
Problem git pushing in the forked repository

### ISSUE THREAD

**Issue by juanessao2000** [escape2020/school2021#60]
![image](https://user-images.githubusercontent.com/85579769/121460581-c6946200-c972-11eb-9abc-1472fd2dfbfc.png)

My question is the last one that is shown in the screenshot

**Comment by Yash-10** [comment]
Hello @juanessao2000,

I think you might have to add your fork as a remote repository using

```
git remote add origin <url_of_forked_repo>
```
where `url_of_forked_repo` can be found on your fork under the "Code" button in green as shown below:

![Screenshot from 2021-06-10 11-04-27](https://user-images.githubusercontent.com/68844397/121470386-c5e3e600-c9db-11eb-99b0-b0fdbf63a9c3.png)


then you could confirm that it was added as a remote by using:

```
git remote -v
```

After this, you could successfully `push` to your fork. Could you please confirm if this helps?

Thanks!

**Comment by garciagenrique** [comment]
Is this issue solved @juanessao2000 ? We will close it if so.

**Comment by maxnoe** [comment]
@garciagenrique Yes, I think we solved it in the slack

**Comment by juanessao2000** [comment]
sorry, I didn' t see the commentaries in the issue until now

git remote -v shows me this
![image](https://user-images.githubusercontent.com/85579769/121588471-9218b880-c9fb-11eb-936d-b5208a0db7a9.png)

Before doing `git remote -v` I made a push with `git push -u origin main` and it seems to have work, because I added a file to the directory `git` and showed me the file in my forked repository in github and not in the original repository of the school

![image](https://user-images.githubusercontent.com/85579769/121588670-d0ae7300-c9fb-11eb-85c7-bd51a9937dc5.png)
![image](https://user-images.githubusercontent.com/85579769/121588709-dad07180-c9fb-11eb-9279-06decd9bab45.png)
![image](https://user-images.githubusercontent.com/85579769/121588768-ec197e00-c9fb-11eb-81bb-51161d7cedb6.png)
![image](https://user-images.githubusercontent.com/85579769/121588797-f50a4f80-c9fb-11eb-9c31-f5cdf55e5cf8.png)
