### ISSUE TITLE
Docker Installation Issues on Linux Mint

### ISSUE THREAD

**Issue by stirfryannie** [escape2020/school2021#63]
I've tried to follow the installation instructions for docker. 
First I attempted the repository installation method. 

```
(base) sc381@papc-sc381:~$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
gpg: WARNING: unsafe ownership on homedir '/home/sc381/.gnupg'

(base) sc381@papc-sc381:~$ echo \
>   "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
>   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```
After this apt is updated and seems to have an issue with keys.. Lots of errors (some mentioning spotify which is a bit disconcerting), but relevant ones are:

```
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58
Hit:11 http://packages.linuxmint.com tina Release                              
Ign:12 https://download.docker.com/linux/ubuntu tina InRelease                 
Err:13 https://download.docker.com/linux/ubuntu tina Release                   
  404  Not Found [IP: 13.224.84.106 443]
.
.
.
.
E: The repository 'https://download.docker.com/linux/ubuntu tina Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Attempting to apt-get install then fails as the packages are missing

```
sudo apt-get install docker-ce docker-ce-cli containerd.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
```

I then attempted to download the .deb file and install that way, however do not know which distribution to use as I run Linux Mint and this doesn't have an exact support in their directory. I note that my linux release UBUNTU codename is 'bionic', so tried to install from the .deb file for the bionic release, but really did not know which file I was looking for in their directory of package files

I'm not sure what has caused the issues (if I'm honest I'm definitely a novice in terms of package installation on linux, despite being fairly advanced in code). 
  

**Desktop (please complete the following information):**
NAME="Linux Mint"
VERSION="19.2 (Tina)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.2"
VERSION_ID="19.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tina
UBUNTU_CODENAME=bionic

**Comment by JulienPeloton** [comment]
Hi @stirfryannie - I never tried on Linux Mint, but I've heard the procedure have changed between 19.2 and 19.3. What installation procedure you were following (you did not mention the link)?

**Comment by stirfryannie** [comment]
Hi @JulienPeloton , my mistake. I followed the procedures described here: https://docs.docker.com/engine/install/ubuntu/

**Comment by JulienPeloton** [comment]
Yes, that's the procedure for `ubuntu`. Can you try instead:

```
# or use Vim, or Emacs, or your favourite one
sudo nano /etc/apt/sources.list.d/additional-repositories.list
```

and add the following line at the end:

```
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```

and finally:

```
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
```

**Comment by stirfryannie** [comment]
Just done this now. 
Still have the same issues. 

Here's the full output. Odd that spotify is also mentioned.. 


(base) sc381@papc-sc381:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:4 http://ppa.launchpad.net/webupd8team/atom/ubuntu bionic InRelease
Get:5 http://repository.spotify.com stable InRelease [3,316 B]
Hit:6 http://dl.google.com/linux/chrome/deb stable InRelease
Get:7 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Ign:8 http://packages.linuxmint.com tina InRelease          
Hit:9 http://archive.canonical.com/ubuntu bionic InRelease  
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:12 http://packages.linuxmint.com tina Release           
Err:5 http://repository.spotify.com stable InRelease        
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58
Hit:13 https://packages.microsoft.com/repos/ms-teams stable InRelease
Ign:14 https://download.docker.com/linux/ubuntu tina InRelease
Err:7 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Err:17 https://download.docker.com/linux/ubuntu tina Release
  404  Not Found [IP: 13.224.84.108 443]
Hit:16 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done 
W: GPG error: http://repository.spotify.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D1742AD60D811D58
E: The repository 'http://repository.spotify.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://download.docker.com/linux/ubuntu tina Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
(base) sc381@papc-sc381:~$ sudo apt-get install docker-ce docker-ce-cli container.io
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce-cli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce-cli' has no installation candidate
E: Unable to locate package container.io
E: Couldn't find any package by glob 'container.io'
E: Couldn't find any package by regex 'container.io'

**Comment by FevenM-Hu** [comment]
Hi @stirfryannie. If you are using the repository installation method, I think you should follow these this steps because of your OS (Linux mint) is a bit different.

1.  sudo apt-get update

2. sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
3.  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
4. echo \  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \  $(bionic) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
5.  sudo apt-get update
6. sudo apt-get install docker-ce docker-ce-cli containerd.io

Then you can continue the next steps.

**Comment by stirfryannie** [comment]
Hi @FevenM-Hu, these lines were run (wiht the only difference being \ $(bionic) stable" was entered as (lsb_release -cs)

I note that after the curl command is entered and run, I get the 'WARNING: unsafe ownership on homedir 'home/sc381/.gnupg' message 
gpg: WARNING: unsafe ownership on homedir '/home/sc381/.gnupg'

Would this one change make that difference?

**Comment by FevenM-Hu** [comment]
Hi @stirfryannie,  the link you have mentioned earlier (https://docs.docker.com/engine/install/ubuntu/) recommend to change  (lsb_release -cs) to (bionic) for Linux Mint Tessa. So, it will make a difference if you start again with those steps.

**Comment by stirfryannie** [comment]
I was under the impression this was for debian based Mint only?

**Comment by stirfryannie** [comment]
Running now

**Comment by stirfryannie** [comment]
Seems I now have a working installation. Cheers!
