### ISSUE TITLE
Problem loading solution_6 at scipy tutorial.

### ISSUE THREAD

**Issue by Gianuzzi** [escape2020/school2021#68]
Cell [55] is: 
```python
# %load solution_6.py
```
, and I think it should be:
```python
 # %load solutions/solution_6.py
```

Also, in solutions/solution_6.py, I think 
```python
date, temperature = np.loadtxt('./munich_temperatures_average.txt', unpack=True)
```
should be replaced with
```python
date, temperature = np.loadtxt('./data/munich_temperatures_average.txt', unpack=True)
```
(Cell [62] (solution_4) has both problems too.)

Also, in a slightly different topic (but same ```.ipynb```), I was wondering if the lines
```python
ax = Axes3D(fig)
```
could be replaced with
```python
ax = Axes3D(fig, auto_add_to_figure=False)
fig.add_axes(ax)
```
in order to avoid the deprecation Warning.

**Comment by vuillaut** [comment]
pinging @adonath

**Comment by maxnoe** [comment]
@Gianuzzi 

Actually, noadays you don't need to use the `Axes3D` object anymore, you can just specify a projection like this:

```
ax = fig.add_subplot(1, 1, 1, projection='3D')
```

**Comment by adonath** [comment]
Thanks a lot @Gianuzzi! I can confirm both issues and the fix as well. If you feel like you could open a PR to implement the proposed fixes, otherwise I can do it myself next Monday.
