### ISSUE TITLE
Astronomical Libraries

### ISSUE THREAD

**Issue by kabartay** [escape2020/school2021#72]
I didn't find tutorials on these nice libs below**:
- [AstroML](http://www.astroml.org/) - a [module](https://pypi.org/project/astroML/) for machine learning and data mining. It contains a growing library of statistical and machine learning routines for analyzing astronomical data in Python, loaders for several open astronomical datasets, and a large suite of examples of analyzing and visualizing astronomical datasets.
- [3ML](https://threeml.readthedocs.io/en/stable/) - a multi-mission maximum likelihood [framework](https://pypi.org/project/threeML/) that provides a common high-level interface and model definition, which allows for an easy, coherent and intuitive modeling of sources using all the available data, no matter their origin.
- [SunPy](https://sunpy.org/) - a [package](https://pypi.org/project/sunpy/) for solar physics.
- [APLpy](https://aplpy.github.io/) - a [module](https://pypi.org/project/APLpy/) aimed at producing publication-quality plots of astronomical imaging data in FITS format.
- [SpecViz](https://specviz.readthedocs.io/en/stable/) - a [tool](https://pypi.org/project/specviz/) for visualization and quick-look analysis of 1D astronomical spectra.

**Note: I am sorry if already covered, but in case not, then I would wish to see it in the next school releases.

**Comment by bkmgit** [comment]
Thanks for the suggestions. Some of the tools in AstroML and SpecViz will be useful for the machine learning module, though due to time constraints and breadth of content, we will not go into depth in them. Note that AstroML does have an accompanying [book](http://www.amazon.com/Statistics-Mining-Machine-Learning-Astronomy/dp/0691198306/).

**Comment by bkmgit** [comment]
https://github.com/escape2020/school2021/pull/73

**Comment by vuillaut** [comment]
> I didn't find tutorials on these nice libs below**:
> 
> * [AstroML](http://www.astroml.org/) - a [module](https://pypi.org/project/astroML/) for machine learning and data mining. It contains a growing library of statistical and machine learning routines for analyzing astronomical data in Python, loaders for several open astronomical datasets, and a large suite of examples of analyzing and visualizing astronomical datasets.
> * [3ML](https://threeml.readthedocs.io/en/stable/) - a multi-mission maximum likelihood [framework](https://pypi.org/project/threeML/) that provides a common high-level interface and model definition, which allows for an easy, coherent and intuitive modeling of sources using all the available data, no matter their origin.
> * [SunPy](https://sunpy.org/) - a [package](https://pypi.org/project/sunpy/) for solar physics.
> * [APLpy](https://aplpy.github.io/) - a [module](https://pypi.org/project/APLpy/) aimed at producing publication-quality plots of astronomical imaging data in FITS format.
> * [SpecViz](https://specviz.readthedocs.io/en/stable/) - a [tool](https://pypi.org/project/specviz/) for visualization and quick-look analysis of 1D astronomical spectra.
> 
> **Note: I am sorry if already covered, but in case not, then I would wish to see it in the next school releases.

Thank you very much for the suggestions.

**Comment by vuillaut** [comment]
> I didn't find tutorials on these nice libs below**:
> 
> * [AstroML](http://www.astroml.org/) - a [module](https://pypi.org/project/astroML/) for machine learning and data mining. It contains a growing library of statistical and machine learning routines for analyzing astronomical data in Python, loaders for several open astronomical datasets, and a large suite of examples of analyzing and visualizing astronomical datasets.
> * [3ML](https://threeml.readthedocs.io/en/stable/) - a multi-mission maximum likelihood [framework](https://pypi.org/project/threeML/) that provides a common high-level interface and model definition, which allows for an easy, coherent and intuitive modeling of sources using all the available data, no matter their origin.
> * [SunPy](https://sunpy.org/) - a [package](https://pypi.org/project/sunpy/) for solar physics.
> * [APLpy](https://aplpy.github.io/) - a [module](https://pypi.org/project/APLpy/) aimed at producing publication-quality plots of astronomical imaging data in FITS format.
> * [SpecViz](https://specviz.readthedocs.io/en/stable/) - a [tool](https://pypi.org/project/specviz/) for visualization and quick-look analysis of 1D astronomical spectra.
> 
> **Note: I am sorry if already covered, but in case not, then I would wish to see it in the next school releases.

Thank you very much for the suggestions.

**Comment by adonath** [comment]
Thanks @kabartay! Many of them are actually Astropy affiliated packages, one could include a section with a quick demo on some of the packages in the next Astropy tutorial, however in general there are way to many packages to show all...
